language: node_js
node_js:
- '7'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "LaztsY8zMIFrcKqjfT+dRWtC5HdpYFxSaOpYCdvUJWEDLxDxh9Ux77DLHow6YrwqAoYX4r3H0em3LWS3nZsSPTe02Xg3piIojYR3KdTO7GFEskWpOw4FTELnNeBWcGM1aCl9tevwloF/M05wjTg5VO91sQ48hI/u5oJyd8JuEpv4Y0QX4nLfZr2ELXrI+7i40UfNx/F/rzoeG6pNgFF1hezkDqUNVIn8Nv2DCJ/B6kK6T9GTZzO1qG4S/6Z6BJEGaBt0/LADoh1PE3TJOTfL7CS8Bq0QNiH3tyPFVzrPXE3JRcPqUGjzk9ZMRRLzBSkHsqtp2uX+GA/N/bctcRD5xRdiDOX5rFPb8m05ve+asoDzwvdu7Dnx+QdqPGHei2QX5wPkBFGrfIfeX9vtBD5LPWstrtw/Eyy9sRcWhf49Wu0fjQlVyv0BD0AU7X9K4ZnYgGXNkVngXcGlBEA9LCbK5W222Cl4TVe4JKTioAc6gnk+CguKO4VLcn1ENH1qyh630jk44LV4dV1MkFpXqv+YQ76t6Pokcfzq3H7j7EdZ9aMQjllUXW9MIP3SCUwR/yBKcV9luE4jFLiH9b/W073MfbWHcgzbIsNq1wUGdbKZsmuFhweogcAvbRjChh8jVSmzgHzb2AHpQMwY1BiJc5vgvXaygdUqEMXNn23nd7OIe7U="
