language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "YTFT5U911PoPYalOXTt36henSROARDBiWhEBwy/PziuZc9Gf+HeB82Yz/OpztOxML0j/HsZTppfWCz0Ma4o4BDsgvR23xb1D1gs/Mq85xOy93QXICD40Z50QqhS4oprSifvV7Spkz8Jqx17E4Ge4Pmv+gMt+UX8+hwQwLDfZ3aXq34DpUPpALIzcyMRXCIMjNMA1F8yGJN3t9bTzI4cFZreM0bJAHylRFXejpcoQ5uwMa5yEaWEsOpQ7Jl2jLm8QyQwvD7wBkDdS6F7bCp3WYtwgKkXmB7LHoPR/OZyfLmltVn5QOe8NCMGkas6RYno7q779ALG1ajSjDcoVQMwgBQ8FwCbZR64O7/TQ+SvEDgHdIwihpaMePQqohcXxirO8SSKvQ4da+A1qUpJWPBWix1Wy1RvXND+OWMRr8PEr0Yzuez1b0eYWX4HQyKdROp6lfQ/W3jg7D+M4muxR42Z1oFTZDsSdRxcQXeYALIOe0fw0nMz6vA5i3p/aNVHm6gW0Sx8ML9AFnVbWOS+tF4g1lLHNHyIRteCNzAbhIZFpMdxToTA91DrW9jZn5A+rJ4sRGBGMFb65mRH2c9o0/Ow5fU2dNvlCWQx+hwBOFThDaypOX6rmbjKOsE/cbA8sd0J0kWDK00kstHdfBEZlPQw5NLM80CvR6yF+2IyWSpAlvMc="
